# Generated by Django 4.0.5 on 2022-06-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('category', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('info', models.TextField(max_length=300)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
